### ISSUE TITLE
Broken promises!

### ISSUE THREAD

**Issue by BattleSpunk** [xDimGG/node-steamapi#10]
Hey,
In your resolve function, if the ID is already in the resolvecache, it will break on a page refresh as it's not resolving the promise.
`if (this.resolveCache.has(id)) return this.resolveCache.get(id);`

**Comment by xDimGG** [comment]
Fixed in https://github.com/xDimGG/node-steamapi/commit/ed74b20c61030c17baff5ff5174d7e56070baf24, silly oversight on my end since I was only using await in my tests.
