### ISSUE TITLE
Incorrect Header Check on Apps List

### ISSUE THREAD

**Issue by gardusi** [xDimGG/node-steamapi#15]
I tried to fetch my apps list and got this error. The request itself returned 200 OK and the data I needed.

> Uncaught (in promise) Error: incorrect header check
>     at Zlib._handle.onerror (index.js:361)
>     at Zlib.push../node_modules/browserify-zlib/lib/binding.js.Zlib._error (binding.js:290)
>     at Zlib.push../node_modules/browserify-zlib/lib/binding.js.Zlib._checkError (binding.js:261)
>     at Zlib.push../node_modules/browserify-zlib/lib/binding.js.Zlib._after (binding.js:270)
>     at binding.js:124
>     at Item.push../node_modules/node-libs-browser/node_modules/process/browser.js.Item.run (browser.js:167)
>     at drainQueue (browser.js:131)

**Comment by AllanPinheiroDeLima** [comment]
Sure af no one is gonna answer this one, right ? What did you do to move on ? I'm having the same problem

**Comment by patkub** [comment]
This works for me to get a list of my own games:
```
steam.getUserOwnedGames('76561197989862681').then((data) => {
    console.log(data);
})
```
steam.getUserOwnedGames won't include free-to-play games (tf2, csgo, etc.). You can use the custom get method to also include free games in your games list like so:
```
steam.get(util.format("/IPlayerService/GetOwnedGames/v0001/?steamid=%s&include_appinfo=1&include_played_free_games=1&format=json", '76561197989862681')).then((data) => {
    console.log(data);
})
```
Other request parameters are detailed here: https://developer.valvesoftware.com/wiki/Steam_Web_API#GetOwnedGames_.28v0001.29

**Comment by xDimGG** [comment]
Not sure what might have caused this but please update as I've switched to using node-fetch. Sorry for the extremely late response. I'll just go ahead and close the issue.
