### ISSUE TITLE
TypeError: Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by NicWickman** [xDimGG/node-steamapi#16]
>  TypeError: Cannot read property 'map' of undefined
>      at get.then.json (D:\Apps\coop\functions\node_modules\steamapi\src\SteamAPI.js:326:38)
>      at process._tickCallback (internal/process/next_tick.js:68:7)

This was working earlier. Suddenly broke?

**Comment by rclafferty** [comment]
@NicWickman I'm having this exact issue. Do you remember what you did to fix your issue a year ago?

**Comment by VeqsaGit** [comment]
> @NicWickman I'm having this exact issue. Do you remember what you did to fix your issue a year ago?

Same... do you have any idea?
