### ISSUE TITLE
CORS modification support

### ISSUE THREAD

**Issue by EOussama** [xDimGG/node-steamapi#17]
I've been trying to get around this error:

```
No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

It would be cool if we were able to modify the headers of the request.

**Comment by xDimGG** [comment]
You can change the `headers` property on the `SteamAPI` class after instantiating it. https://github.com/xDimGG/node-steamapi/blob/84043e55e071724ce4ea0a286052e447c2781d64/src/SteamAPI.js#L37
