### ISSUE TITLE
Question: Is this lib still mantained?

### ISSUE THREAD

**Issue by HOllarves** [xDimGG/node-steamapi#20]
I sent a couple of PRs a week ago, but no response so far :(

Since I'm using this lib for a project I wouldn't mind helping maintain it.

What do you guys say?

**Comment by ArchanjoJr** [comment]
@HOllarves I think this is pretty much dead...
the last commit 84043e5 was over 6 months ago, 
if you want, i could help you maintain this lib as well 
what do you think @xDimGG ?
