### ISSUE TITLE
Add Keyv caching to allow for cached values to be stored externally and not in memory

### ISSUE THREAD

**Issue by Ortovoxx** [xDimGG/node-steamapi#29]
[Keyv](https://www.npmjs.com/package/keyv) allows integration with the current Map api used but also provides external storage of cached values in something like Redis or MongoDB.

I can write the integration but didn't know if you think this is a good idea so thought I would check before I wrote it in.

**Comment by Ortovoxx** [comment]
No worries mate, might make a PR in the future but ovbiously this would be optional.

**Comment by xDimGG** [comment]
After thinking about it, I'm in favor of this change. Do you think you could join the Discord server for a quick chat? https://discord.gg/6d698nhnKx. I just have a few questions about Keyv

**Comment by xDimGG** [comment]
Closing as stale. Feel free to make this PR if you would like.
