### ISSUE TITLE
api can get all previous persona names ?

### ISSUE THREAD

**Issue by maprangsoft** [xDimGG/node-steamapi#39]
how to get all previous persona names ?
example from websie:  [https://steamid.uk/profile/76561198070662042](https://steamid.uk/profile/76561198070662042)

<img width="446" alt="Screen Shot 2565-09-01 at 21 47 44" src="https://user-images.githubusercontent.com/25447955/187944201-51da0bc6-10d8-4268-8123-d4d97d678f64.png">

thank you advance.

**Comment by xDimGG** [comment]
I don't believe this is really supported by the Steam API. After doing a bit of searching, I found this unofficial endpoint `https://steamcommunity.com/id/AGONiZEAXiOM/ajaxaliases`, which may be of interest to you. The past aliases you showed in that screenshot are most likely only stored by steamid.uk and not by Steam. steamid.uk seems to have its own API you can use but that is outside of the scope of this project.
