### ISSUE TITLE
gameDetails in canada please

### ISSUE THREAD

**Issue by zosky** [xDimGG/node-steamapi#42]
when you have time - would you please add `cc=ca` 

[src/SteamAPI.js#L18](https://github.com/xDimGG/node-steamapi/blob/master/src/SteamAPI.js#L18)

`const reRegion = /^us|es|de|fr|ru|nz|au|uk$/i;`

**Comment by xDimGG** [comment]
Added in https://github.com/xDimGG/node-steamapi/commit/31d3ff994a6b7328399bd8d93379185da109c519
