### ISSUE TITLE
Crab Champions fails assertApp()

### ISSUE THREAD

**Issue by x3cion** [xDimGG/node-steamapi#48]
Hey, assertApp() checks for % 10, but Crab Champion's ID is 774801: https://store.steampowered.com/app/774801/Crab_Champions/

I don't know what docs this modulo check is from, but maybe it's obsolete now?

**Comment by xDimGG** [comment]
Oh that's pretty strange. I read somewhere that Steam apps always end in a 0 and 1-9 is reserved for other stuff like DLCs. I checked a few games on Steam store and it appeared to be true, but I guess not. I'll just remove this check. Thanks for letting me know.

**Comment by xDimGG** [comment]
Fixed in 9724f2192f87f0b623906188f4a4b5416b2c5c47
