### ISSUE TITLE
getServerList Always Returns 100 Results, Incorrect Variable Name

### ISSUE THREAD

**Issue by joshuafhiggins** [xDimGG/node-steamapi#51]
Regardless of the number passed in for 'count', the function always returns 100 results. This is because the correct variable name in the Steam API request should actually be 'limit'. If limit is not specified, Steam will always return 100 results.

**Comment by xDimGG** [comment]
Thank you for bringing up the issue. You are correct. I've left a comment on your PR I can merge once that's corrected.

**Comment by joshuafhiggins** [comment]
> Thank you for bringing up the issue. You are correct. I've left a comment on your PR I can merge once that's corrected.

I've fixed the docstring, its all set!
