### ISSUE TITLE
Idea: make resolve support SteamID3

### ISSUE THREAD

**Issue by PixelHir** [xDimGG/node-steamapi#6]
I noticed that resolve function doesn't work with SteamID3 like this: [U:1:128525166]

Would be great if we get feature like that

**Comment by EOussama** [comment]
While you're at that, make it support every possible identifier:

- Profile URL
- Profile permalink
- Steam ID
- Steam ID64
- Steam ID32
- Steam ID3

This page can be of good use: https://developer.valvesoftware.com/wiki/SteamID

I'll see if I can put out an implementation and then issue a pull request.
