### ISSUE TITLE
lack of es5 build in npm package breaks out-of-the-box build from create-react-app

### ISSUE THREAD

**Issue by bdefore** [xDimGG/node-steamapi#9]
```
→ npm run build

> react-scripts build

Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file: 

        ./node_modules/steamapi/src/structures/Player.js:1 

Read more here: http://bit.ly/2tRViJ9
```
The link there explains what needs to be done in order to be compatible: http://bit.ly/2tRViJ9

**Comment by bdefore** [comment]
i can confirm that the workaround mentioned in the article does work:

copy `node_modules/steamapi` to your `src` directory and then import that via relative path i.e.: `const SteamAPI = require('./vendor/steamapi/src/SteamAPI')`

still would be nice to have an es5 build in the package

**Comment by ShayBox** [comment]
es5 is old, stop using it 💢

**Comment by gloss-water** [comment]
@ShayBox CRA targets es5 (ie9+). it's not an unreasonable request since it would allow them to avoid ejecting

**Comment by ShayBox** [comment]
Good meme

**Comment by gloss-water** [comment]
thanks

**Comment by bdefore** [comment]
the workaround no longer works with a project upgraded to newly released CRA2, which seems to not like module exports. specifically requiring a vendor directory of node-steamapi fails on: `TypeError: Cannot assign to read only property 'exports' of object '#<Object>'` from Achivements.js

**Comment by xDimGG** [comment]
Not really familiar with this myself. I'll leave it up to someone else to support this if they choose.
